services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: app_db
    volumes:
      - database-data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@email.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - '16543:80'
    depends_on:
      - db

volumes:
  database-data:
