services:
  app:
    build:
      context: .
      args:
        - ENTRIES_FILE_PATH="~/notes/expenses.json"
    environment:
      - ENTRIES_FILE_PATH="~/notes/expenses.json"
    ports:
      - 3000:3000
    volumes:
      - app-data:/app

volumes:
  app-data:
